#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image:
  - Ubuntu2004

# set clone depth
clone_depth: 5                      # clone entire repository history if not defined

# There is no building process
build: off

# scripts that run after cloning repository
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - source activate
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set auto_update_conda no
  - conda update -q conda
  
  # Set environment variables  
  - MAIN_FOLDER=`pwd`
  
  # Setup the conda environment
  - conda env update -n biorbd -f environment.yml
  - conda activate biorbd
  - conda install pytest-cov black pytest pytest-cov codecov -cconda-forge
  - conda list
  
  
# to run your custom scripts instead of automatic tests
test_script:
  - black . -l120
  - pytest -v --color=yes --cov-report term-missing --cov=bioptim tests
  - python setup.py install
  - cd
  - python -c "import osim_to_biomod"
  - cd $MAIN_FOLDER


#---------------------------------#
#        global handlers          #
#---------------------------------#

# on successful build
on_success:
  - codecov

